---
version: "3.8"
services:
  movies:
    image: sumitra822/paytmmovies:latest
    ports:
      - 81:80
    deploy:
      replicas: 3
  train:
    image: sumitra822/paytmtrain:latest
    ports:
      - 82:80
    deploy:
      replicas: 3
  dth:
    image: sumitra822/paytmdth:latest
    ports:
      - 83:80
    deploy:
      replicas: 3
  recharge:
    image: sumitra822/paytmrecharge:latest
    ports:
      - 84:80
    deploy:
      replicas: 3
