---
version: "3.8"
services:
  movies:
    image: sumitra822/paytmmovies:latest
    ports:
      - 86:80
    deploy:
      replicas: 3
  train:
    image: sumitra822/paytmtrain:latest
    ports:
      - 87:80
    deploy:
      replicas: 3
  dth:
    image: sumitra822/paytmdth:latest
    ports:
      - 88:80
    deploy:
      replicas: 3
  recharge:
    image: sumitra822/paytmrecharge:latest
    ports:
      - 89:80
    deploy:
      replicas: 3
